<?php
session_start();
$disabled=__DIR__.'/storage/installed.lock'; if(file_exists($disabled)){http_response_code(403); exit('Installer disabled.');}
$errors=[];$ok=false;
function req($k,$d=''){return trim($_POST[$k]??$d);} 
function schema(PDO $pdo){
$tables=[];
$tables[]="CREATE TABLE IF NOT EXISTS users(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120),email VARCHAR(190) UNIQUE,password_hash VARCHAR(255),role VARCHAR(30) DEFAULT 'admin',created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";
$tables[]="CREATE TABLE IF NOT EXISTS settings(`key` VARCHAR(120) PRIMARY KEY,`value` TEXT,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";
$tables[]="CREATE TABLE IF NOT EXISTS watchlist(id INT AUTO_INCREMENT PRIMARY KEY,symbol VARCHAR(20) UNIQUE,enabled TINYINT DEFAULT 1,position_size DECIMAL(14,2) DEFAULT 1000,strategy_id INT NULL,notes TEXT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";
$tables[]="CREATE TABLE IF NOT EXISTS strategies(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120),description TEXT,entry_rules TEXT,exit_rules TEXT,tp DECIMAL(8,4),sl DECIMAL(8,4),trailing_stop DECIMAL(8,4),ai_required TINYINT DEFAULT 1,enabled TINYINT DEFAULT 1,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";
$tables[]="CREATE TABLE IF NOT EXISTS paper_accounts(id INT PRIMARY KEY,balance DECIMAL(16,2),equity DECIMAL(16,2),buying_power DECIMAL(16,2),updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";
$tables[]="CREATE TABLE IF NOT EXISTS positions(id INT AUTO_INCREMENT PRIMARY KEY,symbol VARCHAR(20),qty DECIMAL(16,6),avg_price DECIMAL(16,6),market_price DECIMAL(16,6),broker VARCHAR(50) DEFAULT 'paper',updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY sym_broker(symbol,broker)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";
$tables[]="CREATE TABLE IF NOT EXISTS orders(id INT AUTO_INCREMENT PRIMARY KEY,symbol VARCHAR(20),side VARCHAR(10),type VARCHAR(20),qty DECIMAL(16,6),limit_price DECIMAL(16,6) NULL,stop_price DECIMAL(16,6) NULL,status VARCHAR(30),provider VARCHAR(50) DEFAULT 'paper',raw JSON NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,filled_at DATETIME NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";
$tables[]="CREATE TABLE IF NOT EXISTS trades(id INT AUTO_INCREMENT PRIMARY KEY,order_id INT NULL,symbol VARCHAR(20),side VARCHAR(10),qty DECIMAL(16,6),price DECIMAL(16,6),pnl DECIMAL(16,2) DEFAULT 0,reason VARCHAR(255),created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";
$tables[]="CREATE TABLE IF NOT EXISTS ai_decisions(id INT AUTO_INCREMENT PRIMARY KEY,symbol VARCHAR(20),decision VARCHAR(10),confidence DECIMAL(5,2),reasoning TEXT,input_json JSON,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";
$tables[]="CREATE TABLE IF NOT EXISTS webhook_events(id INT AUTO_INCREMENT PRIMARY KEY,source VARCHAR(80),event_type VARCHAR(80),payload JSON,valid TINYINT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";
$tables[]="CREATE TABLE IF NOT EXISTS logs(id INT AUTO_INCREMENT PRIMARY KEY,channel VARCHAR(40),level VARCHAR(20),message TEXT,context JSON NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,INDEX(channel),INDEX(level)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";
$tables[]="CREATE TABLE IF NOT EXISTS journal(id INT AUTO_INCREMENT PRIMARY KEY,trade_id INT NULL,symbol VARCHAR(20),notes TEXT,tags VARCHAR(255),screenshot VARCHAR(255),ai_review TEXT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";
$tables[]="CREATE TABLE IF NOT EXISTS audit_logs(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NULL,action VARCHAR(120),details TEXT,ip VARCHAR(64),created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";
foreach($tables as $sql)$pdo->exec($sql);
}
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(PHP_VERSION_ID<80200)$errors[]='PHP 8.2+ required';
 foreach(['host','db','user','admin_email','admin_password'] as $k) if(!req($k))$errors[]="$k required";
 if(!$errors) try{$pdo=new PDO('mysql:host='.req('host').';charset=utf8mb4',req('user'),req('pass'),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$pdo->exec('CREATE DATABASE IF NOT EXISTS `'.str_replace('`','',req('db')).'` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');$pdo->exec('USE `'.str_replace('`','',req('db')).'`');schema($pdo);
 $stmt=$pdo->prepare('INSERT INTO users(name,email,password_hash) VALUES(?,?,?)');$stmt->execute([req('admin_name','Admin'),req('admin_email'),password_hash(req('admin_password'),PASSWORD_DEFAULT)]);
 $settings=['broker.provider'=>'paper','market.provider'=>'paper','ai.provider'=>'openai','ai.model'=>'gpt-4o-mini','ai.confidence_threshold'=>'70','trading.enabled'=>'0','trading.paper_mode'=>'1','trading.real_mode'=>'0','trading.max_position_size'=>'1000','trading.max_daily_loss'=>'250','trading.max_open_positions'=>'5','trading.max_daily_trades'=>'10','trading.market_hours'=>'09:30-16:00','trading.allow_after_hours'=>'0','webhook.secret'=>bin2hex(random_bytes(16)),'email.from'=>'noreply@example.com'];
 $ins=$pdo->prepare('REPLACE INTO settings(`key`,`value`) VALUES(?,?)');foreach($settings as $k=>$v)$ins->execute([$k,$v]);
 $pdo->exec("INSERT INTO strategies(name,description,entry_rules,exit_rules,tp,sl,trailing_stop,ai_required,enabled) VALUES('Default Momentum','VWAP and volume momentum','Price above VWAP; volume confirmation','Exit on TP/SL or AI sell',0.03,0.015,0.01,1,1)");$sid=$pdo->lastInsertId();
 $wl=$pdo->prepare('INSERT INTO watchlist(symbol,strategy_id,notes) VALUES(?,?,?)');foreach(['AAPL','NVDA','AMZN','TSLA','META','MSFT','NFLX','GOOGL'] as $s)$wl->execute([$s,$sid,'Default watchlist']);
 $pdo->exec('INSERT INTO paper_accounts(id,balance,equity,buying_power) VALUES(1,100000,100000,100000)');
 @mkdir(__DIR__.'/config',0755,true);@mkdir(__DIR__.'/storage/logs',0755,true);@mkdir(__DIR__.'/storage/uploads',0755,true);
 file_put_contents(__DIR__.'/config/config.php','<?php return '.var_export(['db'=>['host'=>req('host'),'name'=>req('db'),'user'=>req('user'),'pass'=>req('pass'),'charset'=>'utf8mb4'],'app'=>['base_url'=>'/signalpilot','installed'=>true,'secret'=>bin2hex(random_bytes(32))]],true).';');
 file_put_contents($disabled,date('c')); rename(__FILE__,__DIR__.'/install.disabled.php'); $ok=true;
 }catch(Throwable $e){$errors[]=$e->getMessage();}}
?><!doctype html><html><head><title>SignalPilot Install</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-dark text-light"><main class="container py-5"><h1>SignalPilot Installer</h1><?php if($ok):?><div class="alert alert-success">Installed. Delete install.disabled.php if desired. <a href="public/index.php">Open app</a></div><?php else: foreach($errors as $e)echo '<div class="alert alert-danger">'.htmlspecialchars($e).'</div>';?><form method="post" class="card bg-secondary p-4"><input class="form-control mb-2" name="host" placeholder="MySQL Host" value="localhost"><input class="form-control mb-2" name="db" placeholder="Database" value="signalpilot"><input class="form-control mb-2" name="user" placeholder="DB User"><input class="form-control mb-2" name="pass" placeholder="DB Password" type="password"><input class="form-control mb-2" name="admin_name" placeholder="Admin Name" value="Admin"><input class="form-control mb-2" name="admin_email" placeholder="Admin Email"><input class="form-control mb-2" name="admin_password" placeholder="Admin Password" type="password"><button class="btn btn-primary">Install</button></form><?php endif;?></main></body></html>
