<?php
session_start(); require __DIR__.'/../app/bootstrap.php';
$page=$_GET['page']??'dashboard';
if($page==='login' && $_SERVER['REQUEST_METHOD']==='POST'){$s=DB::pdo()->prepare('SELECT * FROM users WHERE email=?');$s->execute([$_POST['email']??'']);$u=$s->fetch();if($u&&password_verify($_POST['password']??'',$u['password_hash'])){session_regenerate_id(true);$_SESSION['uid']=$u['id'];header('Location:?');exit;}$err='Invalid login';}
if($page==='logout'){session_destroy();header('Location:?page=login');exit;}
if($page!=='login')auth();
function header_ui($title){echo '<!doctype html><html><head><title>SignalPilot</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-dark text-light"><nav class="navbar navbar-expand bg-black navbar-dark"><a class="navbar-brand ms-3" href="?">SignalPilot</a><div class="navbar-nav"><a class="nav-link" href="?page=settings">Settings</a><a class="nav-link" href="?page=watchlist">Watchlist</a><a class="nav-link" href="?page=strategies">Strategies</a><a class="nav-link" href="?page=orders">Orders</a><a class="nav-link" href="?page=journal">Journal</a><a class="nav-link" href="?page=logs">Logs</a><a class="nav-link" href="?page=reports">Reports</a><a class="nav-link" href="?page=logout">Logout</a></div></nav><main class="container-fluid p-4"><h1>'.e($title).'</h1>';}
function footer_ui(){echo '</main></body></html>';}
if($page==='login'){header_ui('Login'); if(isset($err))echo '<div class="alert alert-danger">'.e($err).'</div>'; echo '<form method="post" class="card bg-secondary p-4 col-md-4"><input name="email" class="form-control mb-2" placeholder="Email"><input type="password" name="password" class="form-control mb-2" placeholder="Password"><button class="btn btn-primary">Login</button></form>'; footer_ui(); exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){check_csrf(); if($page==='settings'){foreach($_POST as $k=>$v)if($k!=='csrf')set_setting(str_replace('__','.',$k),$v);audit('settings_update');} if($page==='watchlist'){DB::pdo()->prepare('REPLACE INTO watchlist(id,symbol,enabled,position_size,strategy_id,notes) VALUES(?,?,?,?,?,?)')->execute([$_POST['id']?:null,strtoupper($_POST['symbol']),isset($_POST['enabled'])?1:0,$_POST['position_size'],$_POST['strategy_id']?:null,$_POST['notes']]);} if($page==='strategies'){DB::pdo()->prepare('REPLACE INTO strategies(id,name,description,entry_rules,exit_rules,tp,sl,trailing_stop,ai_required,enabled) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([$_POST['id']?:null,$_POST['name'],$_POST['description'],$_POST['entry_rules'],$_POST['exit_rules'],$_POST['tp'],$_POST['sl'],$_POST['trailing_stop'],isset($_POST['ai_required'])?1:0,isset($_POST['enabled'])?1:0]);} if($page==='journal'){DB::pdo()->prepare('INSERT INTO journal(trade_id,symbol,notes,tags,ai_review) VALUES(?,?,?,?,?)')->execute([$_POST['trade_id']?:null,$_POST['symbol'],$_POST['notes'],$_POST['tags'],$_POST['ai_review']]);} header('Location:?page='.$page);exit;}
header_ui(ucfirst($page)); $pdo=DB::pdo();
if($page==='dashboard'){$acct=$pdo->query('SELECT * FROM paper_accounts WHERE id=1')->fetch();echo '<div class="row"><div class="col"><div class="card bg-secondary p-3">Balance $'.e($acct['balance']??0).'</div></div></div><h2>Positions</h2><table class="table table-dark">';foreach($pdo->query('SELECT * FROM positions') as $r)echo '<tr><td>'.e($r['symbol']).'</td><td>'.e($r['qty']).'</td><td>'.e($r['avg_price']).'</td></tr>';echo '</table>';}
elseif($page==='settings'){echo '<form method="post"><input type="hidden" name="csrf" value="'.csrf().'">';foreach(['broker.provider','broker.api_key','broker.secret','broker.account_id','market.provider','market.api_key','market.rate_limits','ai.provider','ai.model','ai.api_key','ai.confidence_threshold','email.smtp_host','email.smtp_port','email.smtp_username','email.smtp_password','email.encryption','email.from','email.notify','trading.enabled','trading.paper_mode','trading.real_mode','trading.max_position_size','trading.max_daily_loss','trading.max_open_positions','trading.max_daily_trades','trading.market_hours','trading.allow_after_hours'] as $k)echo '<label>'.e($k).'</label><input class="form-control mb-2" name="'.str_replace('.','__',$k).'" value="'.e(setting($k,'')).'">';echo '<button class="btn btn-success">Save</button></form>';}
elseif($page==='watchlist'){echo '<form method="post" class="row"><input type="hidden" name="csrf" value="'.csrf().'"><input type="hidden" name="id"><div class="col"><input name="symbol" class="form-control" placeholder="Symbol"></div><div class="col"><input name="position_size" class="form-control" value="1000"></div><div class="col"><input name="strategy_id" class="form-control" placeholder="Strategy ID"></div><div class="col"><input name="notes" class="form-control" placeholder="Notes"></div><div class="col"><label><input type="checkbox" name="enabled" checked> Enabled</label><button class="btn btn-primary">Save</button></div></form><table class="table table-dark mt-3">';foreach($pdo->query('SELECT * FROM watchlist') as $r)echo '<tr><td>'.e($r['symbol']).'</td><td>'.e($r['enabled']).'</td><td>'.e($r['position_size']).'</td><td>'.e($r['notes']).'</td></tr>';echo '</table>';}
elseif($page==='strategies'){echo '<form method="post"><input type="hidden" name="csrf" value="'.csrf().'"><input type="hidden" name="id"><input name="name" class="form-control mb-2" placeholder="Name"><textarea name="description" class="form-control mb-2" placeholder="Description"></textarea><textarea name="entry_rules" class="form-control mb-2" placeholder="Entry rules"></textarea><textarea name="exit_rules" class="form-control mb-2" placeholder="Exit rules"></textarea><input name="tp" class="form-control mb-2" placeholder="TP"><input name="sl" class="form-control mb-2" placeholder="SL"><input name="trailing_stop" class="form-control mb-2" placeholder="Trailing"><label><input type="checkbox" name="ai_required" checked> AI Required</label><label><input type="checkbox" name="enabled" checked> Enabled</label><button class="btn btn-primary">Save</button></form><table class="table table-dark">';foreach($pdo->query('SELECT * FROM strategies') as $r)echo '<tr><td>'.e($r['id']).'</td><td>'.e($r['name']).'</td><td>'.e($r['enabled']).'</td></tr>';echo '</table>';}
elseif(in_array($page,['orders','logs','reports','journal'])){if($page==='journal')echo '<form method="post"><input type="hidden" name="csrf" value="'.csrf().'"><input name="trade_id" class="form-control mb-2" placeholder="Trade ID"><input name="symbol" class="form-control mb-2" placeholder="Symbol"><input name="tags" class="form-control mb-2" placeholder="Tags"><textarea name="notes" class="form-control mb-2" placeholder="Notes"></textarea><textarea name="ai_review" class="form-control mb-2" placeholder="AI Review"></textarea><button class="btn btn-primary">Add</button></form>'; $table=$page==='orders'?'orders':($page==='logs'?'logs':($page==='journal'?'journal':'trades')); echo '<table class="table table-dark table-sm">';foreach($pdo->query("SELECT * FROM $table ORDER BY id DESC LIMIT 200") as $r){echo '<tr>';foreach($r as $v)echo '<td>'.e($v).'</td>';echo '</tr>';}echo '</table>';}
footer_ui();
